[general]
modems=2

[network]
puerto=3020

[itu]
format=01
lab=ROA
rev_date=2022-09-14
estacion1=ROA01  LA: N 36 27 51.530       LO: W 006 12 22.333   HT: +0074.67 m
estacion2=ROA02  LA: N 36 27 51.225       LO: W 006 12 22.335   HT: +0074.98 m
frame_ref=WGS-84
loc-mon=NO
modem=SATRE,448
comentarios=CHIP RATES (LINKS 19 and 21): 2.5 Mchip/s    MODEM SW VER 4.15.2 DATE 2008-09-27
ntl=119

[estacion ROA01]
nombre=ROA01

[estacion ROA02]
nombre=ROA02

[link 21]
satelite=TELSTAR 11N
nlo=E 322 27 00.000
xpndr=999999999 ns
SAT-NTX=11497.0600 MHz
SAT-NRX=14047.7400 MHz
bw=3.9 MHz

[link 23]
satelite=TELSTAR 11N
nlo=E 322 27 00.000
xpndr=999999999 ns
SAT-NTX=11497.0600 MHz
SAT-NRX=14047.7400 MHz
bw=3.9 MHz

[cal 571]
tipo=TRIANGLE CLOSURE
mjd=59397
incert=2.000

[cal 579]
tipo=TRIANGLE CLOSURE
mjd=59397
incert=1.400

[cal 599]
tipo=PORT ES REL
mjd=60583
incert=0.500

[cal 609]
tipo=PORT ES REL
mjd=60583
incert=0.500

[cal 618]
tipo=PORT ES REL
mjd=60583
incert=0.800

[cal 627]
tipo=PORT ES REL
mjd=60583
incert=0.800

[cal 634]
tipo=PORT ES REL
mjd=60583
incert=0.500

[cal 640]
tipo=PORT ES REL
mjd=60583
incert=0.500

[cal 646]
tipo=PORT ES REL
mjd=60583
incert=0.800

[cal 647]
tipo=PORT ES REL
mjd=60583
incert=0.600

[cal 648]
tipo=PORT ES REL
mjd=60583
incert=0.700

[cal 649]
tipo=PORT ES REL
mjd=60583
incert=0.800

[cal 650]
tipo=PORT ES REL
mjd=60583
incert=0.500


[mail]
server=roasf2.roa
from=lee_satres@hora
to=luisba@roa.es

[ficheros]
base=/var/log/satres
#1s=/var/log/satres/1s
head1s=header1s.55521
#rp=/var/log/satres/rp

#[Labs CAL]
#letra=z
#minuto=4

[DEFAULT]
local=False
esdvar=999999999
esig=99999

[Lab PL01]
nombre=PL01
letra=p
minuto=0
prn=10
link=14
calr=0
esdvar=0
ci=0
sw=1
refdelay=0

[Lab ROA01]
nombre=ROA01
local=True
letra=k
prn=7
minuto=3
link=14
calr=999999999
ci=999
sw=9
refdelay=0.000000787157
rsig=0.050

[Lab IT02]
nombre=IT02
letra=j
minuto=6
prn=17
link=14
calr=307.700
ci=375
sw=1
refdelay=0

[Lab IT01]
nombre=IT01
letra=i
minuto=9
prn=6
link=14
calr=307.700
esdvar=0
ci=375
sw=1
refdelay=0

[Lab OCA01]
nombre=OCA01
letra=f
minuto=12
prn=5
link=14
calr=999999999
ci=999
sw=9
refdelay=0

[Lab PTB05]
nombre=PTB05
letra=e
minuto=15
prn=4
link=14
calr=-675.200
esdvar=0
ci=380
sw=1
refdelay=0

[Lab SP01]
nombre=SP01
letra=d
minuto=18
prn=3
link=14
calr=32.100
esdvar=0
ci=382
sw=1
refdelay=0

[Lab VSL01]
nombre=VSL01
letra=c
minuto=21
prn=2
link=14
calr=310.189
esdvar=0
ci=404
sw=1
refdelay=0

[Lab NPL02]
nombre=NPL02
letra=b
minuto=24
prn=1
link=14
calr=0
esdvar=0
ci=0
sw=1
refdelay=0

[Lab OP01]
nombre=OP01
letra=a
minuto=27
prn=0
link=14
calr=7145.000
esdvar=0
ci=378
sw=1
refdelay=0

[Lab TIM01]
nombre=TIM01
letra=t
minuto=30
link=14
calr=999999999
esdvar=0
ci=999
sw=9
refdelay=0

[Lab CH01]
nombre=CH01
letra=n
minuto=33
prn=9
link=14
calr=38.238
esdvar=0
ci=399
sw=1
refdelay=0

[Lab NPL01]
nombre=NPL01
letra=z
minuto=36
prn=21
link=14
calr=0
esdvar=0
ci=0
sw=1
refdelay=0

[Lab AOS01]
nombre=AOS01
letra=q
minuto=39
prn=11
link=14
calr=0
ci=0
sw=1
refdelay=0

[Lab MOB02]
nombre=MOB02
letra=v
minuto=42
prn=31
link=14
calr=0
ci=0
sw=1
refdelay=0

[Lab PTB04]
nombre=PTB04
letra=s
minuto=45
prn=24
link=14
calr=-43.100
ci=369
sw=1
refdelay=0

[Lab SP02]
nombre=SP02
letra=d
minuto=48
prn=20
link=14
calr=-612.600
ci=363
sw=1
refdelay=0

[Lab USNO01]
nombre=USNO01
letra=h
minuto=51
prn=7
link=16
calr=-173.652
esdvar=0
ci=403
sw=1
refdelay=0

[Lab NIST01]
nombre=NIST01
letra=g
minuto=54
prn=6
link=16
calr=42.110
esdvar=0
ci=407
sw=1
refdelay=0

[Lab UME01]
nombre=UME01
letra=x
minuto=57
prn=19
link=23
calr=42.110
ci=407
sw=1
refdelay=0


# Horas impares

[Lab ROA11]
nombre=ROA11
letra=k
local=True
minuto=64
link=14
calr=999999999
ci=999
sw=9
refdelay=0.000000787157

[Lab IT11]
nombre=IT11
letra=j
minuto=67
link=14
calr=307.700
ci=375
sw=1
refdelay=0

[Lab PTB11]
nombre=PTB11
letra=e
minuto=70
link=14
calr=-675.200
ci=380
sw=1
refdelay=0

[Lab MOB12]
nombre=MOB12
letra=v
minuto=73
link=14
calr=999999999
ci=999
sw=9
refdelay=0

[Lab IT12]
nombre=IT12
letra=i
minuto=76
link=14
calr=307.700
ci=375
sw=1
refdelay=0

[Lab SP11]
nombre=SP11
letra=d
minuto=79
link=14
calr=32.100
ci=382
sw=1
refdelay=0

[Lab OP11]
nombre=OP11
letra=a
minuto=82
link=14
calr=7145.000
ci=378
sw=1
refdelay=0

[Lab TIM11]
nombre=TIM11
letra=t
minuto=85
link=14
calr=999999999
ci=999
sw=9
refdelay=0
